# fly.toml app configuration file generated for mango-stickies on 2023-11-21T20:29:16-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mango-stickies"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
